### ISSUE TITLE
Deleting cdap_namespace fails

### ISSUE THREAD

**Issue by jasonmcboyd** [GoogleCloudPlatform/terraform-provider-cdap#83] opened 2020-05-21 22:15 UTC
# Problem
Executing `terraform destroy` on a `cdap_namespace` resource fails with the following error:

> Error: 405:
> <!DOCTYPE html>
> <html lang=en>
>   <meta charset=utf-8>
>   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
>   <title>Error 405 (Method Not Allowed)!!1</title>
>   <style>
>     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
>   </style>
>   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
>   <p><b>405.</b> <ins>That’s an error.</ins>
>   <p>  <ins>That’s all we know.</ins>

# Version
Terraform v0.12.24
+ provider.cdap v0.6.0
+ provider.google-beta v3.22.0

# Minimum Code To Reproduce

Apply the following terraform script:

```terraform
provider "google-beta" {
  credentials = "<credentials>"
  project     = "<project-id>"
  region      = "us-west1"
}

resource "google_data_fusion_instance" "instance" {
  provider = google-beta
  name     = "example"
  region   = "us-west1"
  type     = "BASIC"
}

data "google_client_config" "current" {
  provider = google-beta
}

provider "cdap" {
  host  = "${google_data_fusion_instance.instance.service_endpoint}/api/"
  token = data.google_client_config.current.access_token
}

resource "cdap_namespace" "dev" {
  provider = cdap
  name     = "dev"
}
```

Try to destroy everything or just the individual resource:

```bash
terraform destroy -target cdap_namespace.dev
```

**Comment by umairidris** [comment] 2020-05-21 22:23
@jasonmcboyd currently it is not possible to delete namespaces by default. If you want this feature you can add option `{"enable.unrecoverable.reset" = "true"}` on the CDF instance.

**Comment by jasonmcboyd** [comment] 2020-05-21 22:24
Ah, I see. Thanks!

**Comment by jasonmcboyd** [comment] 2020-05-21 22:27
Perhaps the provider could be updated to convey that message when attempting to delete a namespace in a CDF that does not have that option enabled?

**Comment by umairidris** [comment] 2020-05-22 03:30
Happy to accept quality of life improvement PRs!

**Comment by jasonmcboyd** [comment] 2020-07-01 01:51
That's fair! Unfortunately I have no experience with Go. Not yet anyway, it's on my list of things I would like to learn :)

**Comment by jsmilani** [comment] 2023-02-16 23:12
I hit this snag too, but we set `{"enable.unrecoverable.reset" = "true"}` and it still fails with 405. From what I can tell the docs (https://cloud.google.com/data-fusion/docs/reference/cdap-reference#delete_a_namespace) indicate the url to delete the namespace is `"${CDAP_ENDPOINT}/v3/unrecoverable/namespaces/namespace-id"`, but the provider code uses `addr := urlJoin(config.host, "/v3/namespaces", name)`. I tested with curl and confirmed getting a 405 from /v3/namespaces/my-namespace but 200 from /v3/unrecoverable/namespaces/my-namespace.

Seems like deleting the resource is currently not possible with the latest CDAP provider even if `{"enable.unrecoverable.reset" = "true"}` is set due to the different path. It seems like a simple change I can submit a PR for, but I am not sure how to test the binary in our cloudbuild since I cannot run terraform apply from my development environment.

**Comment by umairidris** [comment] 2023-02-17 19:51
@jsmilani your fix is now released in v0.11.0, PTAL!

**Comment by jsmilani** [comment] 2023-02-18 00:39
@umairidris Thanks. I just did a test and verified deleting a namespace works!

**Comment by jsmilani** [comment] 2023-02-18 00:47
The issue with deleting the actual namespace is resolved assuming the option `{"enable.unrecoverable.reset" = "true"}` is set. Based on my recent experience there are some complications changing that attribute that makes it very undesirable to automatically set it when trying to delete a namespace. I found that google terraform provider notices the option changed on the resource and wants to recreate the instance because differences in `options` triggers `forces replacement`. If you update the options in your resource at the same time then it is safe, but it also seems to trigger an update of the instance and takes it offline for a few minutes which blocks the APIs altogether then ends up adding some additional options a few minutes later so more `forces replacement`. Short answer is that is currently too dangerous. I suggest we handle issues with changing options separately and close this.

**Comment by umairidris** [comment] 2023-02-18 02:17
Thanks for the update @jsmilani!

Agreed that we can close this issue since deleting namespaces is now possible.

Looking at the CDF instance resource in the Google provider what you mentioned seems correct, changing options will force recreation of the instance rather than updating it:
https://github.com/hashicorp/terraform-provider-google/blob/beb950ee0d0d0eb580dd0b24f8f8778676c16545/google/resource_data_fusion_instance.go#L174

I suggest filing a bug for the provider and following up there.

Thanks and have a great weekend.

**Closed by umairidris** 2023-02-18 02:17 UTC
